### ISSUE TITLE
Motion Detection causes Homebridge to crash

### ISSUE THREAD

**Issue by mriksman** [luisiam/homebridge-foscamcamera#25]
This used to work fine, I'm not sure when it started failing; possibly after I did the latest npm update -g homebridge-foscamcamera on Thursday 24th November;

```
[11/27/2016, 12:41:21 PM] [Foscam2] C2 Motion Detected!
[11/27/2016, 12:41:21 PM] [Foscam2] Foscam-NG: Getting snapshot.
[11/27/2016, 12:41:21 PM] [Foscam2] Foscam-NG: Getting snapshot.
[11/27/2016, 12:41:21 PM] [Foscam2] Foscam-NG: Got snapshot.
[11/27/2016, 12:41:22 PM] [Foscam2] Foscam-NG: Got snapshot.
[11/27/2016, 12:41:32 PM] [Foscam2] Foscam-NG: Getting snapshot.
[11/27/2016, 12:41:32 PM] [Foscam2] Foscam-NG: Got snapshot.
/usr/local/lib/node_modules/homebridge-foscamcamera/index.js:411
    thisCamera.resetMotion = null;
                           ^

TypeError: Cannot set property 'resetMotion' of undefined
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-foscamcamera/index.js:411:28)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)

```

**Comment by mriksman** [comment]
#24
