### ISSUE TITLE
Plugin Loading SyntaxError

### ISSUE THREAD

**Issue by kskenyon** [luisiam/homebridge-foscamcamera#39]
Apr 10 18:59:27 raspberrypi3 homebridge[6356]: [Mon Apr 10 2017 18:59:27 GMT-0400 (EDT)] ====================
Apr 10 18:59:27 raspberrypi3 homebridge[6356]: [Mon Apr 10 2017 18:59:27 GMT-0400 (EDT)] ERROR LOADING PLUGIN homebridge-foscamcamera:
Apr 10 18:59:27 raspberrypi3 homebridge[6356]: [Mon Apr 10 2017 18:59:27 GMT-0400 (EDT)] SyntaxError: Unexpected token =
Apr 10 18:59:27 raspberrypi3 homebridge[6356]: at exports.runInThisContext (vm.js:53:16)
Apr 10 18:59:27 raspberrypi3 homebridge[6356]: at Module._compile (module.js:414:25)
Apr 10 18:59:27 raspberrypi3 homebridge[6356]: at Object.Module._extensions..js (module.js:442:10)
Apr 10 18:59:27 raspberrypi3 homebridge[6356]: at Module.load (module.js:356:32)
Apr 10 18:59:27 raspberrypi3 homebridge[6356]: at Function.Module._load (module.js:311:12)
Apr 10 18:59:27 raspberrypi3 homebridge[6356]: at Module.require (module.js:366:17)
Apr 10 18:59:27 raspberrypi3 homebridge[6356]: at require (module.js:385:17)
Apr 10 18:59:27 raspberrypi3 homebridge[6356]: at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-foscamcamera/node_modules/homebridge-foscam-stream/node_modules/foscam-binary-client/index.js:6:26)
Apr 10 18:59:27 raspberrypi3 homebridge[6356]: at Module._compile (module.js:435:26)
Apr 10 18:59:27 raspberrypi3 homebridge[6356]: at Object.Module._extensions..js (module.js:442:10)
Apr 10 18:59:27 raspberrypi3 homebridge[6356]: [Mon Apr 10 2017 18:59:27 GMT-0400 (EDT)] ====================

**Comment by kskenyon** [comment]
switched to node 7.8.0 and the error went away.  Still can't connect to the camera.

**Comment by luisiam** [comment]
What do you mean by `can't connect to the camera`? Do you see the camera in the HomeKit app?
