### ISSUE TITLE
No Stream

### ISSUE THREAD

**Issue by theo-69** [luisiam/homebridge-foscamcamera#42]
Hi there everything is working, I can arm my cam and getting notification with snapshot, however the Stream is not working rtsp is working. Its a Foscam FI9900P!

`[6/28/2017, 2:49:53 PM] [Foscam] FI9900P Motion Detected!
[6/28/2017, 2:49:54 PM] [Foscam] Foscam-NG: Getting snapshot.
[6/28/2017, 2:49:55 PM] [Foscam] Foscam-NG: Got snapshot.
[6/28/2017, 2:49:55 PM] [Foscam] FI9900P is armed (night).
[6/28/2017, 2:49:58 PM] [Foscam] FI9900P is set to disarmed.
[6/28/2017, 3:18:36 PM] [Foscam] Foscam-NG: Getting snapshot.
[6/28/2017, 3:18:36 PM] [Foscam] Foscam-NG: Got snapshot.
[6/28/2017, 3:18:36 PM] [Foscam] FI9900P is disarmed.
[6/28/2017, 3:18:46 PM] [Foscam] Foscam-NG: Getting snapshot.
[6/28/2017, 3:18:47 PM] [Foscam] Foscam-NG: Got snapshot.
[6/28/2017, 3:18:53 PM] [Foscam] FI9900P is set to armed (stay).
[6/28/2017, 3:18:58 PM] [Foscam] Foscam-NG: Getting snapshot.
[6/28/2017, 3:19:19 PM] [Foscam] Foscam-NG: Got snapshot.
[6/28/2017, 3:19:29 PM] [Foscam] Foscam-NG: Getting snapshot.
[6/28/2017, 3:19:30 PM] [Foscam] Foscam-NG: Got snapshot.
Unhandled rejection RequestError: Error: read ECONNRESET
    at new RequestError (/usr/lib/node_modules/homebridge-foscamcamera/node_modules/request-promise/lib/errors.js:11:15)
    at Request.RP$callback [as _callback] (/usr/lib/node_modules/homebridge-foscamcamera/node_modules/request-promise/lib/rp.js:60:32)
    at self.callback (/usr/lib/node_modules/homebridge-foscamcamera/node_modules/request/request.js:188:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at Request.onRequestError (/usr/lib/node_modules/homebridge-foscamcamera/node_modules/request/request.js:884:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at Socket.socketErrorListener (_http_client.js:358:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at emitErrorNT (net.js:1279:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
`

**Comment by theo-69** [comment]
now its not working at all anymore getting
`(node:2642) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Trigger interval 30 is out of range.
(node:2642) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by luisiam** [comment]
#14
