### ISSUE TITLE
Error: Error relocating

### ISSUE THREAD

**Issue by oynek** [luisiam/homebridge-foscamcamera#57]
What is wrong here?

> [2018-1-30 15:20:12] ====================
> [2018-1-30 15:20:12] ERROR LOADING PLUGIN homebridge-foscamcamera:
> [2018-1-30 15:20:12] Error: Error relocating /homebridge/node_modules/foscam-binary-client/build/Release/FoscamG726.node: alaw2linear: symbol not found
>     at Object.Module._extensions..node (module.js:672:18)
>     at Module.load (module.js:556:32)
>     at tryModuleLoad (module.js:499:12)
>     at Function.Module._load (module.js:491:3)
>     at Module.require (module.js:587:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (/homebridge/node_modules/foscam-binary-client/lib/FoscamStreamLayer.js:5:20)
>     at Module._compile (module.js:643:30)
>     at Object.Module._extensions..js (module.js:654:10)
>     at Module.load (module.js:556:32)
> [2018-1-30 15:20:12] ====================

**Comment by th3cube** [comment]
Same Problem here

**Comment by th3cube** [comment]
Anybody have a Solution to this Problem? The Plugin seems to be Broken. Getting an Error when loading the Plugin 

![bildschirmfoto 2018-02-15 um 17 09 18](https://user-images.githubusercontent.com/20889464/36343076-d45c08bc-1407-11e8-83a9-e9b6ebbb345e.png)

Homebridge@0.4.38
npm@5.6.0
node@v8.9.4

**Comment by th3cube** [comment]
@oynek My problem was caused by using Alpine Linux as the base System for a Docker Image which is using musl libc what causes the compatibility issues. **(Thanks to @oznu for finding the Problem)**. 

The Solution was switching to a Debian base which is using glibc. The Developer @oznu provided a Debian version of his Docker-Homebridge Implementation which is solving all problems. So if you are using Docker for Homebridge go check his Project out, its great. https://github.com/oznu/docker-homebridge. Make sure that you Download the Debian Version

**Comment by oynek** [comment]
I actually use @oznu 's homebridge docker image. But I did not find an option to manually choose the type of Linux. Can you point me to the right direction?

**Comment by th3cube** [comment]
Sure. When you pull the Docker image make sure not to use the "latest" tag, as it will download the alpine version. Use the Debian Tag instead. If you are using a Raspberry-Pi use the "debian-raspberry-pi" Tag

https://hub.docker.com/r/oznu/homebridge/tags/

**Comment by CroVlado** [comment]
i get the same issues on the latest release of home assistant installed with the hass.io image
